### ISSUE TITLE
add functionality for coloring line plots

### ISSUE THREAD

**Issue by berceanu** [berceanu/sliceplots#13]

**Comment by berceanu** [comment]
Sometimes it is useful to color the line in a 1D plot depending on the values of another variable. Case in point: When plotting electron betatron trajectories, col.or them proportional to their `gamma` factor.

Skeleton code, courtesy of @hightower8083:

```python
def plot_colored(x, y, c, cmap=plt.cm.jet, steps=5, ax=None, **kw_args):
    if ax is None:
        ax = plt.gca()
    c = np.asarray(c)
    c -= c.min()
    c /= c.max()
    it=0
    while it<c.size-steps:
        x_segm = x[it:it+steps+1]
        y_segm = y[it:it+steps+1]
        c_segm = cmap( c[it+steps//2] )
        ax.plot(x_segm, y_segm, c=c_segm, **kw_args)
        it += steps
```

**Comment by berceanu** [comment]
See also [this example](https://matplotlib.org/3.1.0/gallery/lines_bars_and_markers/multicolored_line.html).

**Comment by hightower8083** [comment]
nice -- i haven't seen this page! 
Seems it does the trick and probably better than `plot_colored`, but they could have pack it into some simple method though..

**Comment by berceanu** [comment]
Thats's why we'll include it into `sliceplots` ;)

**Comment by berceanu** [comment]
@hightower8083 the colored lineplot functionality was added in the latest release, as documented [here](https://sliceplots.readthedocs.io/en/latest/modules/sliceplots.one_dimensional.html#sliceplots.one_dimensional.plot_multicolored_line).

**Comment by hightower8083** [comment]
can it take `vmin`, `vmax` for the colour variable? (in case one needs to make multiple plots with same normalization)

**Comment by berceanu** [comment]
Implemented, along with transparency and colorbar.
